#!/usr/bin/env python3
"""
Canyon — step_alpaca_execution.py
===================================
Alpaca paper-trading execution layer.
Manages three portfolio books (SHORT / MEDIUM / LONG) using the
alpha scores generated by Canyon's signal pipeline.

Safety rules:
  1. PAPER_TRADING_ONLY = True by default — change to False only when ready for live
  2. Position cap: 15% per ticker per book
  3. Max book allocation: SHORT=20%, MEDIUM=30%, LONG=50% of total capital
  4. Only trades S&P 500 tickers (no OTC, no crypto, no options)
  5. Only places LIMIT orders at last price — never market orders
  6. Rebalance frequency guarded: won't rebalance within 70% of the target window

Books:
  SHORT  — top-10 from ml_alpha_scores.ml_short,  rebalance weekly (≥4 trading days)
  MEDIUM — top-15 from ml_alpha_scores.ml_medium, rebalance bi-weekly (≥9 trading days)
  LONG   — top-20 from alpha_scores.alpha_score,  rebalance monthly (≥18 trading days)

Outputs:
  alpaca_book_state.json   current positions, last rebalance, P&L tracking
  alpaca_orders.csv        order log (appended)
"""
from __future__ import annotations

import json
import os
import sys
import warnings
from datetime import datetime, timedelta
from pathlib import Path

import pandas as pd

warnings.filterwarnings("ignore")

ROOT  = Path(__file__).parent
TODAY = datetime.now().strftime("%Y-%m-%d")
NOW   = datetime.now()

GREEN  = "\033[92m"; RED = "\033[91m"; YELLOW = "\033[93m"
CYAN   = "\033[96m"; BOLD = "\033[1m"; RESET  = "\033[0m"

def log(msg): print(f"  {msg}")
def ok(msg):  print(f"  {GREEN}✓{RESET}  {msg}")
def warn(msg):print(f"  {YELLOW}⚠{RESET}  {msg}")
def err(msg): print(f"  {RED}✗{RESET}  {msg}")
def hdr(msg): print(f"\n{BOLD}{CYAN}{msg}{RESET}")


# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────

PAPER_TRADING_ONLY = True       # NEVER set False without explicit live-trading review

# Regime-conditional capital scaling
# When HMM regime = BEAR, multiply each book's capital_pct by this factor
REGIME_SCALE = {
    "BULL":      1.00,
    "LATE_BULL": 0.80,
    "BEAR":      0.35,
}
# Conviction weighting: top pick gets TOP_WEIGHT_MULT × equal weight,
# bottom pick gets 1/TOP_WEIGHT_MULT — linearly interpolated.
CONVICTION_WEIGHT_MULT = 2.0   # range [1.0 = equal-weight, 3.0 = strong conviction tilt]

# Earnings blackout: don't hold through earnings within this many trading days
EARNINGS_BLACKOUT_DAYS = 3

BOOKS = {
    "SHORT": {
        "n_picks":          10,    # top 10 longs + bottom 10 shorts = 20 legs
        "rebalance_days":   5,
        "score_file":       "ml_alpha_scores.csv",
        "score_col":        "ml_short",
        "capital_pct":      0.20,
        "position_cap":     0.15,
        "earnings_filter":  True,
        "long_short":       True,  # buy top N, short bottom N — true market-neutral
    },
    "MEDIUM": {
        "n_picks":          15,
        "rebalance_days":   10,
        # 复活动量为活因子: ml_medium(死ML因子) → exec_score(事件×动量, 前瞻对决证明最强)
        "score_file":       "event_candidates.csv",
        "score_col":        "exec_score",
        "capital_pct":      0.30,
        "position_cap":     0.12,
        "earnings_filter":  False,
    },
    "LONG": {
        "n_picks":          20,
        "rebalance_days":   21,
        # 三脑合一(B→执行): 核心多头由事件OS驱动。exec_score = FinalEventScore × 动量倾斜
        # (前瞻对决证明"事件+动量">纯事件分)。21天再平衡, event_candidates 1天延迟无影响。
        "score_file":       "event_candidates.csv",
        "score_col":        "exec_score",
        "capital_pct":      0.50,
        "position_cap":     0.10,
    },
}

STATE_PATH  = ROOT / "alpaca_book_state.json"
ORDERS_PATH = ROOT / "alpaca_orders.csv"


# ─────────────────────────────────────────────────────────────────────────────
# Earnings blackout filter
# ─────────────────────────────────────────────────────────────────────────────

def get_earnings_blackout_tickers() -> set[str]:
    """Return set of tickers with earnings within EARNINGS_BLACKOUT_DAYS trading days."""
    cal_path = ROOT / "earnings_calendar.csv"
    if not cal_path.exists():
        return set()
    try:
        df = pd.read_csv(cal_path, parse_dates=["earnings_date"])
        if "ticker" not in df.columns or "earnings_date" not in df.columns:
            return set()
        today_dt = pd.Timestamp(TODAY)
        # include today and next N trading days (approx as calendar days × 1.4)
        window_end = today_dt + pd.Timedelta(days=int(EARNINGS_BLACKOUT_DAYS * 1.4) + 1)
        mask = (df["earnings_date"] >= today_dt) & (df["earnings_date"] <= window_end)
        blackout = set(df.loc[mask, "ticker"].dropna().tolist())
        if blackout:
            log(f"  Earnings blackout ({EARNINGS_BLACKOUT_DAYS}d): {', '.join(sorted(blackout)[:8])}"
                f"{'…' if len(blackout)>8 else ''}")
        return blackout
    except Exception:
        return set()


# ─────────────────────────────────────────────────────────────────────────────
# Regime-conditional capital scaling
# ─────────────────────────────────────────────────────────────────────────────

def get_regime_scale() -> float:
    """Read current HMM regime and return capital scale factor."""
    macro_path = ROOT / "macro_signals.json"
    if not macro_path.exists():
        return 1.0
    try:
        macro = json.loads(macro_path.read_text())
        regime = macro.get("hmm_regime", "BULL").upper()
        # Map HMM output to our regime keys
        if "BEAR" in regime or "RISK_OFF" in regime:
            key = "BEAR"
        elif "LATE" in regime:
            key = "LATE_BULL"
        else:
            key = "BULL"
        scale = REGIME_SCALE.get(key, 1.0)
        log(f"  Regime: {regime} → capital scale {scale:.0%}")
        return scale
    except Exception:
        return 1.0


# ─────────────────────────────────────────────────────────────────────────────
# Conviction-weighted position sizing
# ─────────────────────────────────────────────────────────────────────────────

def conviction_weights(scores: pd.Series, n: int, cap: float) -> dict[str, float]:
    """
    Given top-N scores (higher = better), compute conviction weights that
    allocate more capital to higher-ranked picks.

    Uses a linear ramp: rank 1 → TOP_WEIGHT_MULT × equal, rank N → 1/TOP_WEIGHT_MULT × equal.
    Normalises so weights sum to 1, then applies position cap.
    """
    top = scores.nlargest(n)
    tickers = top.index.tolist()
    n_actual = len(tickers)
    if n_actual == 0:
        return {}

    mult = CONVICTION_WEIGHT_MULT
    # raw weights: linearly spaced from mult down to 1/mult
    raw = [mult - (mult - 1.0 / mult) * i / max(n_actual - 1, 1)
           for i in range(n_actual)]
    total_raw = sum(raw)
    weights   = {tk: raw[i] / total_raw for i, tk in enumerate(tickers)}

    # apply position cap
    weights = {tk: min(w, cap) for tk, w in weights.items()}
    # renormalise
    total_w = sum(weights.values())
    if total_w > 0:
        weights = {tk: w / total_w for tk, w in weights.items()}

    return weights


# ─────────────────────────────────────────────────────────────────────────────
# Alpaca client
# ─────────────────────────────────────────────────────────────────────────────

def get_client():
    try:
        from alpaca.trading.client import TradingClient
    except ImportError:
        err("alpaca-py not installed — run: pip install alpaca-py")
        return None

    key    = os.environ.get("ALPACA_KEY_ID", "")
    secret = os.environ.get("ALPACA_KEY_SECRET", "")
    if not key or not secret:
        err("ALPACA_KEY_ID / ALPACA_KEY_SECRET not set — check .env")
        return None

    try:
        client = TradingClient(key, secret, paper=PAPER_TRADING_ONLY)
        account = client.get_account()
        mode = "PAPER" if PAPER_TRADING_ONLY else "LIVE"
        ok(f"Alpaca {mode} account — equity: ${float(account.equity):,.0f}  "
           f"buying power: ${float(account.buying_power):,.0f}")
        return client
    except Exception as e:
        err(f"Alpaca connection failed: {e}")
        return None


def get_equity(client) -> float:
    try:
        return float(client.get_account().equity)
    except Exception:
        return 0.0


def get_positions(client) -> dict[str, float]:
    """Returns {ticker: market_value}"""
    try:
        positions = client.get_all_positions()
        return {p.symbol: float(p.market_value) for p in positions}
    except Exception:
        return {}


def get_latest_prices(client, tickers: list[str]) -> dict[str, float]:
    """Returns {ticker: last_price} via Alpaca data API."""
    try:
        from alpaca.data.historical import StockHistoricalDataClient
        from alpaca.data.requests import StockLatestTradeRequest

        key    = os.environ.get("ALPACA_KEY_ID", "")
        secret = os.environ.get("ALPACA_KEY_SECRET", "")
        data_client = StockHistoricalDataClient(key, secret)

        # batch in chunks of 50
        prices = {}
        for i in range(0, len(tickers), 50):
            batch = tickers[i:i+50]
            try:
                req = StockLatestTradeRequest(symbol_or_symbols=batch)
                resp = data_client.get_stock_latest_trade(req)
                for sym, trade in resp.items():
                    prices[sym] = float(trade.price)
            except Exception:
                pass
        return prices
    except Exception:
        return {}


def place_limit_order(client, ticker: str, qty: float, side: str, price: float) -> bool:
    """Place a limit order. side = 'buy' or 'sell'."""
    try:
        from alpaca.trading.requests import LimitOrderRequest
        from alpaca.trading.enums import OrderSide, TimeInForce

        if qty < 0.001:
            return False

        limit_price = round(price * (1.002 if side == "buy" else 0.998), 2)  # 0.2% slippage buffer
        req = LimitOrderRequest(
            symbol=ticker,
            qty=qty,
            side=OrderSide.BUY if side == "buy" else OrderSide.SELL,
            time_in_force=TimeInForce.DAY,
            limit_price=limit_price,
        )
        order = client.submit_order(req)
        log(f"  ORDER {side.upper()} {qty:.4f}×{ticker} @ ${limit_price:.2f}  id={order.id}")
        _log_order(ticker, side, qty, limit_price, order.id)
        return True
    except Exception as e:
        warn(f"  Order failed {ticker}: {e}")
        return False


def _log_order(ticker, side, qty, price, order_id):
    row = pd.DataFrame([{
        "date": TODAY,
        "time": NOW.strftime("%H:%M:%S"),
        "ticker": ticker,
        "side": side,
        "qty": qty,
        "price": price,
        "order_id": str(order_id),
    }])
    if ORDERS_PATH.exists():
        row.to_csv(ORDERS_PATH, mode="a", header=False, index=False)
    else:
        row.to_csv(ORDERS_PATH, index=False)


# ─────────────────────────────────────────────────────────────────────────────
# Order fill monitoring
# ─────────────────────────────────────────────────────────────────────────────

def cancel_stale_orders(client) -> int:
    """
    Cancel any open limit orders that are more than 1 trading day old.
    Returns count of cancelled orders.
    """
    try:
        from alpaca.trading.requests import GetOrdersRequest
        from alpaca.trading.enums import QueryOrderStatus
        req = GetOrdersRequest(status=QueryOrderStatus.OPEN, limit=200)
        open_orders = client.get_orders(req)
    except Exception as e:
        warn(f"  Could not fetch open orders: {e}")
        return 0

    cancelled = 0
    cutoff = NOW - pd.Timedelta(hours=26)   # >1 trading day old
    for o in open_orders:
        try:
            created = pd.Timestamp(o.created_at)
            if created < cutoff:
                client.cancel_order_by_id(o.id)
                log(f"  Cancelled stale order: {o.side.value} {o.symbol} (age {(NOW-created).days}d)")
                cancelled += 1
        except Exception:
            pass

    if cancelled:
        warn(f"  Cancelled {cancelled} stale unfilled orders")
    else:
        ok(f"  No stale orders to cancel ({len(open_orders)} open orders reviewed)")
    return cancelled


def get_fill_rate(client, lookback_days: int = 5) -> dict[str, float]:
    """Return fill rate per side over last N days."""
    try:
        from alpaca.trading.requests import GetOrdersRequest
        from alpaca.trading.enums import QueryOrderStatus
        since = (NOW - pd.Timedelta(days=lookback_days)).isoformat() + "Z"
        req = GetOrdersRequest(status=QueryOrderStatus.ALL, after=since, limit=500)
        orders = client.get_orders(req)
        total = len(orders)
        filled = sum(1 for o in orders if o.status.value in ("filled", "partially_filled"))
        return {"total": total, "filled": filled,
                "fill_rate": round(filled / max(total, 1), 3)}
    except Exception:
        return {"total": 0, "filled": 0, "fill_rate": 0.0}


# ─────────────────────────────────────────────────────────────────────────────
# State management
# ─────────────────────────────────────────────────────────────────────────────

def load_state() -> dict:
    if STATE_PATH.exists():
        try:
            return json.loads(STATE_PATH.read_text())
        except Exception:
            pass
    return {book: {"last_rebalance": None, "positions": {}} for book in BOOKS}


def save_state(state: dict):
    STATE_PATH.write_text(json.dumps(state, indent=2, default=str))


def should_rebalance(book_name: str, state: dict) -> bool:
    last = state.get(book_name, {}).get("last_rebalance")
    if not last:
        return True
    last_dt = datetime.fromisoformat(last)
    cfg = BOOKS[book_name]
    # guard at 70% of target window to avoid rebalancing too frequently
    min_days = cfg["rebalance_days"] * 0.7
    elapsed = (NOW - last_dt).days
    # convert calendar days to approx trading days (×5/7)
    elapsed_td = elapsed * 5 / 7
    return elapsed_td >= min_days


# ─────────────────────────────────────────────────────────────────────────────
# Score loading
# ─────────────────────────────────────────────────────────────────────────────

def load_scores(book_name: str) -> pd.Series | None:
    cfg = BOOKS[book_name]
    fpath = ROOT / cfg["score_file"]
    if not fpath.exists():
        warn(f"  Score file missing: {cfg['score_file']}")
        return None

    try:
        df = pd.read_csv(fpath)
    except Exception as e:
        err(f"  Cannot read {cfg['score_file']}: {e}")
        return None

    col = cfg["score_col"]
    if "ticker" not in df.columns or col not in df.columns:
        warn(f"  Missing columns in {cfg['score_file']} — need ticker,{col}")
        return None

    scores = df.set_index("ticker")[col].dropna()
    return scores


# ─────────────────────────────────────────────────────────────────────────────
# Rebalance one book
# ─────────────────────────────────────────────────────────────────────────────

def rebalance_book(
    book_name: str,
    client,
    state: dict,
    total_equity: float,
    regime_scale: float,
    earnings_blackout: set[str],
):
    cfg = BOOKS[book_name]
    hdr(f"  Book: {book_name}")

    # 1. Load scores → apply earnings filter → pick top N
    scores = load_scores(book_name)
    if scores is None or len(scores) < cfg["n_picks"]:
        warn(f"  Insufficient scores for {book_name}")
        return

    # Earnings blackout filter (SHORT book only by default)
    if cfg.get("earnings_filter", False) and earnings_blackout:
        n_before = len(scores)
        scores = scores[~scores.index.isin(earnings_blackout)]
        n_filtered = n_before - len(scores)
        if n_filtered:
            log(f"  Earnings filter removed {n_filtered} tickers from SHORT candidates")

    if len(scores) < cfg["n_picks"]:
        warn(f"  Not enough scores after earnings filter — skipping")
        return

    is_long_short = cfg.get("long_short", False)

    if is_long_short:
        # ── True long/short book (SHORT book) ─────────────────────────────
        # Long leg: top N by score (after earnings filter already applied above)
        long_weights = conviction_weights(scores, cfg["n_picks"], cfg["position_cap"])
        # Short leg: bottom N by score (lowest scores = weakest stocks)
        short_scores = scores.copy()
        # Exclude long candidates from short pool
        short_scores = short_scores[~short_scores.index.isin(long_weights.keys())]
        short_weights_raw = conviction_weights(
            short_scores.sort_values().head(cfg["n_picks"]),  # lowest scores first
            cfg["n_picks"], cfg["position_cap"]
        )

        long_tickers  = list(long_weights.keys())
        short_tickers = list(short_weights_raw.keys())
        all_target_tickers = long_tickers + short_tickers
        log(f"  L/S: LONG {', '.join(long_tickers[:3])}… SHORT {', '.join(short_tickers[:3])}…")

        prices = get_latest_prices(client, all_target_tickers)
        valid_longs  = [tk for tk in long_tickers  if tk in prices and prices[tk] > 0]
        valid_shorts = [tk for tk in short_tickers if tk in prices and prices[tk] > 0]

        if not valid_longs and not valid_shorts:
            warn("  No valid prices — skipping")
            return

        # Normalise weights
        def _norm(wts, valid):
            w = {tk: wts[tk] for tk in valid if tk in wts}
            tot = sum(w.values())
            return {tk: v / tot for tk, v in w.items()} if tot > 0 else {}

        lw = _norm(long_weights, valid_longs)
        sw = _norm(short_weights_raw, valid_shorts)

        effective_capital_pct = cfg["capital_pct"] * regime_scale
        book_capital = total_equity * effective_capital_pct
        half_cap = book_capital * 0.5   # 50% long / 50% short
        log(f"  Capital: ${book_capital:,.0f} ({effective_capital_pct:.0%}) — "
            f"${half_cap:,.0f} each leg")

        # Target dollar values: positive = long, negative = short
        target_values = {}
        for tk, w in lw.items():
            target_values[tk] = half_cap * w          # positive → buy
        for tk, w in sw.items():
            target_values[tk] = -half_cap * w         # negative → short sell

        all_positions = get_positions(client)
        current_book_tickers = set(state.get(book_name, {}).get("positions", {}).keys())

        # Close positions no longer in target
        to_close = current_book_tickers - set(target_values.keys())
        for tk in to_close:
            if tk in all_positions and tk in prices:
                mv = all_positions[tk]   # positive = long, negative = short
                qty = abs(mv) / prices[tk]
                side = "sell" if mv > 0 else "buy"  # close long=sell, close short=buy
                place_limit_order(client, tk, qty, side, prices[tk])

        # Adjust to target
        for tk, tgt_val in target_values.items():
            price   = prices.get(tk, 0)
            if price <= 0:
                continue
            cur_val = all_positions.get(tk, 0.0)
            delta   = tgt_val - cur_val
            if abs(delta) < book_capital * 0.01:
                continue
            qty  = abs(delta) / price
            side = "buy" if delta > 0 else "sell"
            place_limit_order(client, tk, qty, side, price)

        state[book_name]["positions"]        = {tk: v for tk, v in target_values.items()}
        state[book_name]["last_rebalance"]   = NOW.isoformat()
        state[book_name]["regime_scale"]     = regime_scale
        state[book_name]["effective_capital"]= round(book_capital, 2)
        state[book_name]["long_tickers"]     = valid_longs
        state[book_name]["short_tickers"]    = valid_shorts

        ok(f"  SHORT book L/S rebalanced — {len(valid_longs)} long + {len(valid_shorts)} short, "
           f"${book_capital:,.0f}")

    else:
        # ── Long-only books (MEDIUM / LONG) ───────────────────────────────
        weights = conviction_weights(scores, cfg["n_picks"], cfg["position_cap"])
        target_tickers = list(weights.keys())
        log(f"  Top picks: {', '.join(target_tickers[:5])} … "
            f"(conviction spread: {min(weights.values())*100:.1f}%–{max(weights.values())*100:.1f}%)")

        prices = get_latest_prices(client, target_tickers)
        valid_tickers = [tk for tk in target_tickers if tk in prices and prices[tk] > 0]
        if not valid_tickers:
            warn("  No valid prices found — skipping")
            return

        valid_w = {tk: weights[tk] for tk in valid_tickers}
        total_w = sum(valid_w.values())
        if total_w > 0:
            valid_w = {tk: w / total_w for tk, w in valid_w.items()}

        effective_capital_pct = cfg["capital_pct"] * regime_scale
        book_capital = total_equity * effective_capital_pct
        log(f"  Capital: ${book_capital:,.0f} ({effective_capital_pct:.0%} × regime {regime_scale:.0%})")

        target_values = {tk: book_capital * w for tk, w in valid_w.items()}

        all_positions = get_positions(client)
        current_book_tickers = set(state.get(book_name, {}).get("positions", {}).keys())

        to_sell = current_book_tickers - set(valid_tickers)
        for tk in to_sell:
            if tk in all_positions and tk in prices:
                mv  = all_positions[tk]
                qty = mv / prices[tk]
                place_limit_order(client, tk, qty, "sell", prices[tk])

        for tk in valid_tickers:
            price     = prices[tk]
            tgt_val   = target_values[tk]
            cur_val   = all_positions.get(tk, 0.0)
            delta_val = tgt_val - cur_val
            if abs(delta_val) < book_capital * 0.01:
                continue
            qty  = abs(delta_val) / price
            side = "buy" if delta_val > 0 else "sell"
            place_limit_order(client, tk, qty, side, price)

        state[book_name]["positions"]        = {tk: target_values[tk] for tk in valid_tickers}
        state[book_name]["last_rebalance"]   = NOW.isoformat()
        state[book_name]["regime_scale"]     = regime_scale
        state[book_name]["effective_capital"]= round(book_capital, 2)

        ok(f"  {book_name} rebalanced — {len(valid_tickers)} positions, "
           f"${book_capital:,.0f} (regime-adjusted)")


# ─────────────────────────────────────────────────────────────────────────────
# Reporting
# ─────────────────────────────────────────────────────────────────────────────

def print_book_report(state: dict, client):
    hdr("Portfolio Status")
    all_pos = get_positions(client)
    total_mv = sum(all_pos.values())

    for book_name in BOOKS:
        book_state = state.get(book_name, {})
        last_reb   = book_state.get("last_rebalance", "never")
        positions  = book_state.get("positions", {})
        book_mv    = sum(all_pos.get(tk, 0) for tk in positions)
        print(f"\n  {BOLD}{book_name}{RESET}")
        print(f"    Last rebalance : {last_reb[:10] if last_reb != 'never' else 'never'}")
        print(f"    Positions      : {len(positions)}")
        print(f"    Market value   : ${book_mv:,.0f}")
        if positions:
            print(f"    Holdings       : {', '.join(list(positions.keys())[:8])}{'…' if len(positions)>8 else ''}")

    print(f"\n  Total portfolio value: ${total_mv:,.0f}")


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main():
    print(f"\n{BOLD}Canyon — Alpaca Execution{'  [PAPER]' if PAPER_TRADING_ONLY else '  ⚠ LIVE'}{RESET}  {TODAY}")

    # Load .env
    env_file = ROOT / ".env"
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                if k.strip() and v.strip() and k.strip() not in os.environ:
                    os.environ[k.strip()] = v.strip()

    client = get_client()
    if client is None:
        return

    total_equity = get_equity(client)
    if total_equity <= 0:
        err("Cannot read account equity")
        return

    state = load_state()

    # Check if market is open
    try:
        clock = client.get_clock()
        if not clock.is_open:
            warn(f"Market is closed (next open: {clock.next_open})")
            warn("Showing current state without placing orders.")
            print_book_report(state, client)
            return
    except Exception:
        warn("Could not check market hours — proceeding anyway")

    # Compute shared inputs once
    regime_scale      = get_regime_scale()
    earnings_blackout = get_earnings_blackout_tickers()
    log(f"  Earnings blackout pool: {len(earnings_blackout)} tickers")

    # Rebalance books that are due
    for book_name in BOOKS:
        if should_rebalance(book_name, state):
            rebalance_book(book_name, client, state, total_equity,
                           regime_scale, earnings_blackout)
        else:
            last = state.get(book_name, {}).get("last_rebalance", "never")
            log(f"  {book_name}: not due for rebalance yet (last: {str(last)[:10]})")

    save_state(state)
    ok("Book state saved → alpaca_book_state.json")

    print_book_report(state, client)
    print(f"\n{GREEN}✓ Alpaca execution complete{RESET}\n")


if __name__ == "__main__":
    main()
